polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),

    path("<int:question_id>/", views.detail, name="detail"),

    # ex: /polls/5/results/
    path("<int:question_id>/result/", views.results, name="result"),

    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

tuto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # include 함수로 polls 앱 자체의 urls.py를 프로젝트에서 사용하도록 등록
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("polls2/", include("polls2.urls")),
]

polls2/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import Question, Choice


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/result.html", {"question": question})


def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def index(request):
    lastest_question_list = Question.objects.all().order_by("-pub_date")[:5]
    # 템플릿 객체
    template = loader.get_template("polls/index.html")
    # 딕셔너리
    context = {
        "latest_question_list": lastest_question_list
    }
    # final_html = template.render(context, request)  # 최종 HTML 생성을 하여 반환 하는것
    # request 반환이유: request를 넘겨주면 로그인한 사용자 정보, 현재 URL, CSRF 토큰 등 다양한 기능을 사용할 수 있음
    return HttpResponse(template.render(context, request))


def vote(request, question_id):
    # get_object_or_404() 내장함수는 히나의 툭정 객체를 가져오거나, 존재하지 않을 결우 자동으로 404 오류메시지를 발생시킴
    # 파라미터로는 모델 클래스, 모델 매니저, QuerySet 중 하나
    # 다수의 객체를 가져오려면 get_list_or_404()
    # hasattr(객체, "속성 는 메서드") <-- 객체가 속성이나, 메서드를 가지고 있으면 True
    # klass 는 Class, Manager, QuerySet 중 하나를 받을 수 있는 변수. --> 왜 class 가 아니고 klass 인 이유는 class 는 파이썬에서 예약어이기 때문임
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        # F() 객체는 데이터베이스 내에서 필드 값을 직접 수정하고, 이 수정된 값을 데이터베이스에 반영하도록 돕는 역할.
        # 예를 예를 들어, F("votes") + 1은 현재 votes 필드 값에 1을 더하는 연산을 데이터베이스에서 바로 수행하도록 함.
        # F("votes")는 데이터베이스 내 votes 필드의 현재 값을 의미. + 1은 그 값을 1 증가시키는 연산을 함.
        # 이 코드는 votes 필드에 대한 값을 메모리에서 처리하는 것이 아니라, db에서 직접 현재 votes 값에 1을 더해서 업데이트하는 방식. 이유는 동시성 문제.
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:result", args=(question.id,)))

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

{#form 요소#}
{#forloop.counter <-- for태그가 반복한 횟수를 나타냄 #}
{#교차 사이트 요청 위조(Cross Site Request Forgeries) 방지를위해 내부 URL을 대상으로 하는 모든 POST 양식은 {% csrf_token %} 템플릿 태그를 사용해야 힘#}

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


{#    <table>#}
{#        {% for x in for_number %}#}
{#            <tr>#}
{#                {% for i in for_number %}#}
{#                    <td>{{ i }}</td>#}
{#                {%  endfor %}#}
{#            </tr>#}
{#        {% endfor %}#}
{#    </table>#}

polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{%  for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>